package main

import (
	"challenges"
)

func main() {
	// challenges.Challenge1()
	// challenges.Challenge2()
	// challenges.Challenge3()
	// challenges.Challenge4()
	// challenges.Challenge5()
	// challenges.Challenge6()
	// challenges.Challenge7()
	// challenges.Challenge8()
	// challenges.Challenge9()
	// challenges.Challenge10()
	// challenges.Challenge11()
	// challenges.Challenge12()
	// challenges.Challenge13()
	// challenges.Challenge14()
	// challenges.Challenge15()
	// challenges.Challenge16()
	// challenges.Challenge17()
	// challenges.Challenge18()
	// challenges.Challenge19()
	// challenges.Challenge20()
	// challenges.Challenge21()
	// challenges.Challenge22()
	// challenges.Challenge23()
	// challenges.Challenge24()
	//challenges.Challenge25()
	// challenges.Challenge26()
	// challenges.Challenge27()
	// challenges.Challenge28()
	// challenges.Challenge29()
	// challenges.Challenge30()
	// challenges.Challenge31()
	// challenges.Challenge32()
	// challenges.Challenge33()
	// challenges.Challenge34()
	// challenges.Challenge35()
	// challenges.Challenge36()
	// challenges.Challenge37()
	// challenges.Challenge38()
	// challenges.Challenge39()
	// challenges.Challenge40()
	// challenges.Challenge41()
	// challenges.Challenge42()
	// challenges.Challenge43()
	// challenges.Challenge45()
	// challenges.Challenge47()
	// challenges.Challenge47()
	// challenges.Challenge48()
	// challenges.Challenge49()
	// challenges.Challenge50()
	// challenges.Challenge51()
	// challenges.Challenge52()
	// challenges.Challenge53()
	// challenges.Challenge54()
	// challenges.Challenge55()
	// challenges.Challenge56()
	// challenges.Challenge57()
	// challenges.Challenge58()
	// challenges.Challenge59()
	// challenges.Challenge60()
	// challenges.Challenge61()
	// challenges.Challenge62()
	challenges.Challenge63()
	// challenges.Challenge67()
}
